* 常见
  保密C
  篡改->完整性I
  ~破坏（丢包）->可用性A~

  等保
  D1，C1，C2 （DAC自主访问控制）
  B1，B2，B3，A1 （MAC强制访问控制）

  PDR (protection detection response) 静态
  PPDR  + ~policy 动态~

  网络安全法2016.11.7 发布
  YD 邮电 / GA 公安

  同步规划，同步建设，同步实施

  ACL（访问控制列表） 客体
  CL（访问能力表） 主体

  SDL软件安全开发生命周期：5+2

  ~网络层提供了保密性，身份鉴别，数据完整性服务~

  权限分离：离职员工，需要两主管人员同时确认

* BLP模型, 机密性-上写下读
  
* Biba模型中完整性，不允许上写

* RBAC
  RBAC0
  RBAC1，基于0，加入等级及角色
  RBAC2，基于0，加入等约束条件
  RBAC3，结合1，2.

* IPSEC 不是一个单独的协议
  AH：验证；ESP：加密

* Kerberos 对称加密
  密钥分发中心，由以下两部分组成
  AS（Authentication Server）：认证服务器
  TGS（Ticket Granting Server）：票证发放服务器

* 鉴别
  基本途径3种：所知（短信认证），所有（智能卡）和个人特征。 ~不包括令牌~

* PGP
  PGP采用了一种RSA和传统加密的杂合.数据压缩、对称密钥加密，以及公钥加密的算法。
  目前，PGP可以支持的操作类型包括 ~数字签名、消息加密、压缩、分段、重组~
  
* IPS入侵检测系统
  串接到网络中，可能会单点故障。
  会影响网络性能

* 信息安全等级保护
  由低到高划分为五个等级。 
  分别是:第一级:用户自主保护级、
  ~第二级:系统审计保护级、 ~公民法人有影响，不危害国家，公共利益~, 只需备案，不需要上级测评检查。
  第三级:安全标记保护级、 ~国家公共利益一定损害~
  第四级:结构化保护级、 ~国家公共利益较大损害~
  第五级:访问验证保护级 ~国家公共利益特别严重损害~

* 计算机取证过程包括 ~4 阶段~
  依次是：保护现场、证据获取、分析、提交结果
  
* 信息系统安全保障模型 4个
  包含保障要素4个（技术、管理、工程和人员）、生命周期和安全特征3个方面

* 国家网络空间安全战略 =4部分=

* 风险评估方法 4个
  基于知识的分析方法
  基于模型的分析方法
  定量分析
  ~定性分析（最广泛的资产评估方法）~

* TODO SABSA 模型 6层
  ~分层模型~ ，第一层从安全角度 ~定义业务需求~

* 应急响应 ~六阶段~
  准备, 确认, 遏制, 根除, 恢复, 跟踪

* TODO CC 是我国信息安全评估的国家标准 7个递增的评估保证等级

* TODO 霍尔三维结构 7阶段和7步骤
  
* BSI模型（Build Security In）
  软件安全三根支柱： ~风险管理，软件安全触点和安全知识~
  #风险知识点#

* CNCI 美国发布，以风险为核心
  
* SSECMM能力成熟度模型
** TODO 测量单位是公共特征（CF）
